name: Release Drafter

on:
  push:
    branches:
      - master
      - '2.1'

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.update_release_draft.outputs.tag_name }}
    steps:
      - name: Draft Release
        id: update_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@master

      # Get the current package.json version number
      - name: Compare Versions
        id: compare_versions
        run: |
          CURRENTVERSION=$(npm version | grep werkbot-framewerk | sed -re "s/[a-z]*//g;s/[-|,|:|']//g;s/\s//g")
          echo "::set-output name=current_version_number::$CURRENTVERSION"
        
      # Update the package.json version number.
      # This only runs when the draft release tag_name differs from the current package.json version number.
      - name: Update package.json version
        if: steps.update_release_draft.outputs.tag_name != steps.compare_versions.outputs.current_version_number
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.update_release_draft.outputs.tag_name }}

      - name: Commit Updated package.json
        if: steps.update_release_draft.outputs.tag_name != steps.compare_versions.outputs.current_version_number
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated package.json
